### ISSUE TITLE
AddUserMetaService seems to be unused

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#25]
Maybe this was originally intended to be used in places like [AvatarAddMetaService.php:69-74](https://github.com/wecodemore/wcm-avatar/blob/b4ecf0e12021015740958a878200c526e915ced8/src/Services/AvatarAddMetaService.php#L69-L74) ?

**Comment by kraftner** [comment]
Current result from in-person discussion with @franz-josef-kaiser : This plugin needs a review of what's necessary and what can be left off to loose weight.

**Comment by kraftner** [comment]
Can we just delete this? Or do you want to actually use it somewhere @franz-josef-kaiser?

**Comment by franz-josef-kaiser** [comment]
Done in #52
