### ISSUE TITLE
Disable Multi-Selection 

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#33]
Currently Plupload allows multi-selection which also causes all files to be uploaded. This is somewhat related to #24.

Using the `plupload_init` filter this could be disabled in the UI.
For the server side of things it seems as if each file is uploaded independently via a separate request, so when #24 is done I'd say everything after the first upload would just fail.

**Comment by franz-josef-kaiser** [comment]
Done with 912d5a3
