### ISSUE TITLE
Multi Uploader breaks when Upload fails

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#36]
To reproduce just try uploading an SVG file.

At first glance it seems as if the response from `async-upload.php` is assumed to always be an image, while this can also be an error message if the upload fails. This is then put in the template where the `<img>` is expected breaking the template somehow.

**Comment by franz-josef-kaiser** [comment]
@kraftner can you please update your issue with a link to the place in code where this is assumed?

**Comment by kraftner** [comment]
[Somewhere in here](https://github.com/wecodemore/wcm-avatar/tree/master/assets/src/logo) :wink:
Haven't wrapped my head around the JS part yet.

**Comment by kraftner** [comment]
fixed by #48
