### ISSUE TITLE
Create *.pot file

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#38]
Whatever [this is](https://github.com/wecodemore/wcm-avatar/blob/b4ecf0e12021015740958a878200c526e915ced8/lang/wcmavatar.pot) it doesn't seem to have anything to do with this plugin.

**Comment by franz-josef-kaiser** [comment]
That's an old left over from the original version. The old version (pre GitHub) did tons of things and the functionality you can see now is what was extracted and open sourced. This is just the old language file, which was responsible for much, much more and needs an update.

**Comment by franz-josef-kaiser** [comment]
I now added [_POEditor.com_](https://poeditor.com/projects/view?id=38517) as integration to this project. I have no idea what will actually happen. The good thing is that the integration showed that there are tons of left over strings – and that translations are created extremely easy with this. 

On top, I improved [the Bash script](https://github.com/wecodemore/wcm-avatar/blob/f97881765c7555d08604900bbf103ed80219130e/create-pot.sh) that was used until now, to have a local fallback. We should remove the left over strings and then make use of the integration. In the best case, we can link to _POEditor.com_ from our README.md file to invite others to provide translations the easy way without installing any software. Please ping me in Slack if you allow me to give you collaborator access to the service. Thanks.

**Comment by kraftner** [comment]
Can we close this? I think a general improvement concerning the left over strings would mandate another ticket.

**Comment by franz-josef-kaiser** [comment]
@kraftner Yes. I just needed to force-fail the `xgettext` bash script to catch log files in the VCS ignore file. Done with d35a38b.
