### ISSUE TITLE
AvatarScriptsService lacks check for permissions

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#43]
[The check](https://github.com/wecodemore/wcm-avatar/blob/58caa432ab5637aabbcc8bd7dfd9a90e5337b0bc/src/Services/AvatarScriptsService.php#L59-L62) does only check if we are on a profile screen, but not if we have the proper rights.

This causes a JS error `TypeError: uploader is undefined` when editing another users profile while not having `upload_files` permission.

Should probably be [something like here](https://github.com/wecodemore/wcm-avatar/blob/58caa432ab5637aabbcc8bd7dfd9a90e5337b0bc/src/Views/UploadView.php#L55-L68).

**Comment by franz-josef-kaiser** [comment]
Done with 6082bd3.
