### ISSUE TITLE
Reconsider using file_get_contents() in UnderscoreTemplateScripts

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#44]
Is it really necessary to use `file_get_contents` with a URL here? Can't we get this from the local filesystem?

Reason why I'm asking is that I've just run into an issue while working on a dev site with a self-signed certificate where this fails as the server (somewhat ironically) isn't aware of his own self-signed certificate.

**Comment by kraftner** [comment]
The more I think about it we probably can't easily get rid of going via the URL as we're sitting on top of `wp_enqueue_script`.

The issue I mentioned probably can and should be fixed with properly configuring the Server...

Anyway I think we should be trying to get the file earlier in that method and do something more graceful than outputting empty templates and a bunch of Warnings.

**Comment by gmazzap** [comment]
@franz-josef-kaiser will hate me for this... but maybe sitting on top of `wp_enqueue_script` is the wrong thing to do...

 `allow_url_fopen` to `off` is a thing that make sense IMO, I would set it like that on _my_ server, and doing that `file_get_contents` with URL will fail anyway.

Surely we could use HTTP API, but honestly there should be a better approach...

**Comment by franz-josef-kaiser** [comment]
@Giuseppe-Mazzapica It's just code and I am not married to it. Every input that makes things better or closes a gap is appreciated. Setting `allow_url_fopen` to `off` is a more than valid approach.

Added both labels now as I am not sure how to treat this and there are no alternatives so far. I need some time and brain to work on it, but currently I am mostly brain dead after work.

**Comment by franz-josef-kaiser** [comment]
@kraftner can you elaborate this?

> Reason why I'm asking is that I've just run into an issue while working on a dev site with a self-signed certificate where this fails as the server (somewhat ironically) isn't aware of his own self-signed certificate.

**Comment by gmazzap** [comment]
My proposal here: https://github.com/wecodemore/wcm-avatar/compare/dev...UnderscoreTemplateEnqueuer

Completely **untested**...

**Comment by franz-josef-kaiser** [comment]
@Giuseppe-Mazzapica LGTM! Can you make that a PR?

**Comment by gmazzap** [comment]
@franz-josef-kaiser Did you take the time to test it? Maybe @kraftner can do it? Also, I think some love on code style is needed...

**Comment by kraftner** [comment]
First of all: Thanks @Giuseppe-Mazzapica !

Okay so I gave this a quick look: First of all have you been too scared of the hate of @franz-josef-kaiser to stick with `wp_enqueue_script`? :wink: 

Secondly I just pushed some changes to actually make that code run. :wink:

**Comment by kraftner** [comment]
So I gave this a short test run - seems like it's working as intended. Thanks again @Giuseppe-Mazzapica !

**Comment by franz-josef-kaiser** [comment]
The last reference above this message here is wrong. I merged the wrong branches (which is fixed and reverted).

**Comment by kraftner** [comment]
already fixed by #46
