### ISSUE TITLE
Remove (apparently) unused AdminStylesService

### ISSUE THREAD

**Issue by kraftner** [wecodemore/wcm-avatar#50]
[Services/AdminStylesService.php](https://github.com/wecodemore/wcm-avatar/blob/58caa432ab5637aabbcc8bd7dfd9a90e5337b0bc/src/Services/AdminStylesService.php) adds [Devicons](http://vorillaz.github.io/devicons/#/main) which as far as I can tell aren't used anywhere. Probably just remove it.

**Comment by franz-josef-kaiser** [comment]
The PR in #51 removed the file, but the call in [`Bootstrap.php`](https://github.com/wecodemore/wcm-avatar/blob/90e16073fbd17a5d626b934af10fdd663ab82206/Bootstrap.php#L180-L183) is still there.

**Comment by franz-josef-kaiser** [comment]
Done with 8f43de8

**Comment by kraftner** [comment]
Oops, sorry,  and thanks for fixing. :+1:
